name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java JDK
  uses: actions/setup-java@v2
  with:
    java-version: 21

    - name: Build with Maven
      run: mvn -B -f project-template/pom.xml clean package

    - name: Checkstyle
      run: mvn -f project-template/pom.xml checkstyle:check
